language: r
cache: packages
r_packages:
  - covr
addons:
  apt:
    packages:
      - libnode-dev
r_github_packages:
  - mrc-ide/cinterpolate
  - ropensci/jsonvalidate
  - mrc-ide/odin
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
