language: r
cache: packages
r_packages:
  - covr
addons:
  apt:
    packages:
      - libv8-dev
r_github_packages:
  - mrc-ide/cinterpolate
  - ropensci/jsonvalidate@use-ajv
  - mrc-ide/odin@i139_ir
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
